### ISSUE TITLE
Include upstream patch in mikeperry-tor/android-simg2img

### ISSUE THREAD

**Issue by anoadragon453** [mikeperry-tor/mission-improbable#10]
I was getting an issue with building android-simg2img in the ./run_all.sh script. 

Turns out a errant `$` was included in it. Once I removed that the script ran beautifully.

I noticed this had already been fixed in the repo's master (https://github.com/mikeperry-tor/android-simg2img/commit/cc129c4d148e20d08002df1ac86fbcd53329d01a) but it hadn't made it to the verity_tools3 branch.

If you could include that patch in the other branch it may prevent some noobs from being confused :)

**Comment by neuhaus** [comment]
What's the verity_tools3 branch?

**Comment by anoadragon453** [comment]
https://github.com/mikeperry-tor/android-simg2img/tree/verity_tools3

**Comment by mikeperry-tor** [comment]
I merged this commit.

**Comment by anoadragon453** [comment]
The commit was merged on master branch hoever the script still pulls from the verity_tools3 branch, thus the bug still occurs.
